spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/securitydb
spring.datasource.username=postgres
spring.datasource.password=Jenny@1$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.paths-to-match=/api/**