spring.application.name=demo

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/securitydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Siddu@2003}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# REDIS
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# SECURITY
spring.main.allow-bean-definition-overriding=true

# MAIL
spring.mail.host=${MAIL_HOST:mailhog}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=cinthiyajenniefer@gmail.com
spring.mail.password=qngqxtzadqrwgmfx
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8
