spring.application.name=demo

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/securitydb
spring.datasource.username=postgres
spring.datasource.password=Jenny@1$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# SECURITY
spring.main.allow-bean-definition-overriding=true

# MAIL (IMPORTANT CLEAN CONFIG)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cinthiyajenniefer@gmail.com
spring.mail.password=qngqxtzadqrwgmfx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8

